#
#	Global configuration for Glib makefiles
#

UNAME := $(shell uname)

ifeq ($(UNAME), Linux)
  # Linux flags
  CC = g++
  CXXFLAGS += -std=c++0x -Wall -fopenmp
  #CXXFLAGS += -O3
  # turn on for crash debugging, get symbols with <prog> 2>&1 | c++filt
  CXXFLAGS += -g -rdynamic
  LDFLAGS +=
  LIBS += -lrt -luuid

else ifeq ($(UNAME), Darwin)
  # OS X flags
  CC = g++
  CXXFLAGS += -std=c++98 -Wall -fopenmp
  CXXFLAGS += -O3
  LDFLAGS +=
  LIBS +=

else ifeq ($(shell uname -o), Cygwin)
  # Cygwin flags
  CC = g++
  CXXFLAGS += -Wall -fopenmp
  CXXFLAGS += -O3
  LDFLAGS +=
  LIBS +=

endif

	